### ISSUE TITLE
service glusterfsd not started nor enabled on RHEL

### ISSUE THREAD

**Issue by Tuxem** [robertdebock/ansible-role-glusterfs#3]
Without this service started, on RHEL, glusterFS seems not to work properly

## Fix proposed

Add this task
```
- name: Start glusterfsd
  ansible.builtin.service:
    name: glusterfsd
    state: started
    enabled: yes

```
## Environment

- RHEL 7
